### ISSUE TITLE
Unable to build with null in g11n.t() function

### ISSUE THREAD

**Issue by kraklin** [Bobris/bobril-build#42]
Bobril build v. 0.64.0

When I used g11n function t with second parameter null, I cannot compile the project with following error.

```
g.t("text to tranlsate",null,"hint text"); // causing error
g.t("text to tranlsate",undefined,"hint text"); // works OK
```

```
D:\workspace\Cloud\cloud-hg\bb\node_modules\bobril-build\dist\buildHelpers.js:134

item.knownParams = params !== undefined && typeof params === "object" ? Object.keys(params) : [];
                                                                                                   ^
TypeError: Cannot convert undefined or null to object
    at visit (D:\workspace\Cloud\cloud-hg\bb\node_modules\bobril-build\dist\buildHelpers.js:134:100)
    at visitNode (D:\workspace\Cloud\cloud-hg\bb\node_modules\typescript\lib\typescript.js:13876:20)
    at Object.forEachChild (D:\workspace\Cloud\cloud-hg\bb\node_modules\typescript\lib\typescript.js:13938:21)
    at visit (D:\workspace\Cloud\cloud-hg\bb\node_modules\bobril-build\dist\buildHelpers.js:152:12)
...
```

**Comment by Bobris** [comment]
Ha it cannot happen with strictNullCheck, why you still don't use it :-)

It shows something like this:
src/app.ts(27,22): error TS2345: Argument of type 'null' is not assignable to parameter of type 'Object | undefined'.
