### ISSUE TITLE
Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by yardee** [Bobris/bobril-build#48]
Hello,
I am getting **Error: Debug Failure. False expression.** everytime I try **recompile** sources (after start bb compiles just fine, but if I change something in sources, I get the error). I happens also in demo bbApp.

console:
Bobril-build 0.80.0 - c:\projekty\demo\bbApp
Server listening on:  http://localhost:8080
Upgrading dependencies...
yarn upgrade v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 4 new dependencies.
├─ bobril-g11n@4.1.0
├─ bobril@8.1.1
├─ moment@2.19.3
└─ normalize.css@3.0.3
Done in 13.98s.
Watching ready in 758ms
Starting compilation.
Compiled in 3710ms. Updated 14 files.
Build finished with 0 warnings. Starting tests.
Tests: 1 failed 0 skipped 4 succeeded
Starting compilation.
Error: Debug Failure. False expression.
Compilation failed in 828ms
(node:9836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Debug Failure. False expression.
(node:9836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yardee** [comment]
It looks it is bug in the Typescript. It happens when calling `let diagnostics = program.getSemanticDiagnostics();` in compilationCache:

```
if (diagnostics.length === 0) {
    let diagnostics = program.getGlobalDiagnostics();
    this.reportDiagnostics(diagnostics);
    if (diagnostics.length === 0) {
        let diagnostics = program.getSemanticDiagnostics(); <---------------
        this.reportDiagnostics(diagnostics);
    }
}

```
stacktrace: 
Error: Debug Failure. False expression.
    at resolveNameHelper (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:24714:30)
    at resolveName (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:24482:20)
    at getResolvedSymbol (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:33849:21)
    at checkIdentifier (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:35154:26)
    at checkExpressionWorker (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40556:28)
    at checkExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40529:42)
    at checkBinaryLikeExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40118:28)
    at checkBinaryExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40111:20)
    at checkExpressionWorker (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40621:28)
    at checkExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40529:42)
    at checkParenthesizedExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40551:20)
    at checkExpressionWorker (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40595:28)
    at checkExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40529:42)
    at checkBinaryLikeExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40119:29)
    at checkBinaryExpression (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40111:20)
    at checkExpressionWorker (C:\Users\mikeb\AppData\Roaming\npm\node_modules\bobril-build\node_modules\typescript\lib\typescript.js:40621:28)

**Comment by Bobris** [comment]
What version of TypeScript are you using? Because I cannot reproduce it.

**Comment by yardee** [comment]
It is version 2.6.2. You are cannot reproduce it in bbApp example?

**Comment by Bobris** [comment]
Yes. I cannot reproduce it in bbApp, maybe it needs to be specific change.

**Comment by yardee** [comment]
I run bb, it compiles just fine, than "fix" the demoSpec ( exampleFailure(3); ) and get the exception during recompile.

**Comment by Bobris** [comment]
Thanks reproduced.

**Comment by Bobris** [comment]
I just fixed this bug with comination of using prefixing of styleDefs and when 3rd parameter of styleDef is not constant. I am not sure your original project has same combination of features, because they are pretty rare. So reopen if new version does not fix your problem.

**Comment by yardee** [comment]
It's fixed, thank you for quick fix.
